
CREATE TABLE [dbo].[T_PersonInfo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PerName] [varchar](50) NULL,
	[PerIdCard] [varchar](50) NULL,
 CONSTRAINT [PK_T_PersonInfo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


